import type { Response } from 'express';
import type { AuthRequest } from '../middleware/auth.js';
import { CANONICAL_TO_LEGACY, LEGACY_TO_CANONICAL, ROLE_LABELS } from '../types/roles.js';
import type { CanonicalRole, LegacyRole } from '../types/roles.js';

type Priority = 'low' | 'medium' | 'high' | 'critical';
type Tone = 'blue' | 'green' | 'amber' | 'red' | 'purple' | 'slate';

interface PersonaPayload {
  role: CanonicalRole;
  legacy_role: LegacyRole;
  title: string;
  subtitle: string;
  mission: string;
  portal_path: string;
  kpis: Array<{ label: string; value: string; trend: string; tone: Tone }>;
  queues: Array<{ title: string; count: number; href: string; priority: Priority; description: string }>;
  alerts: Array<{ title: string; description: string; severity: Priority }>;
  quick_actions: Array<{ label: string; href: string; intent: string }>;
  demo_highlights: Array<{ title: string; body: string; metric: string }>;
  legal_pillars: string[];
}

const basePillars = ['Tài trợ/đặt hàng nhiệm vụ KH&CN', 'Hỗ trợ lãi suất vay', 'Voucher công nghệ', 'Hệ sinh thái khởi nghiệp sáng tạo'];

const data: Record<CanonicalRole, Omit<PersonaPayload, 'role' | 'legacy_role'>> = {
  chief_system_architect: {
    title: 'Không gian kiến trúc hệ thống', subtitle: 'Quản trị blueprint, API, DB schema, module dependency', mission: 'Bảo đảm OMS vận hành theo kiến trúc thống nhất, an toàn, mở rộng được.', portal_path: '/admin/architecture',
    kpis: [{label:'Module đã chuẩn hóa',value:'12/17',trend:'+4 sprint này',tone:'blue'},{label:'API contract',value:'86',trend:'98% có RBAC',tone:'green'},{label:'Nợ kỹ thuật',value:'14',trend:'-6',tone:'amber'},{label:'SLA kiến trúc',value:'99.95%',trend:'ổn định',tone:'purple'}],
    queues: [{title:'Duyệt thay đổi schema',count:5,href:'/admin/architecture/schema',priority:'high',description:'Migration cần rà soát tác động nghiệp vụ'},{title:'API contract pending',count:9,href:'/admin/architecture/apis',priority:'medium',description:'Endpoint cần chuẩn hóa response'}],
    alerts: [{title:'Route legacy còn tồn tại',description:'8 dashboard cũ cần chuyển dần sang persona shell.',severity:'medium'}],
    quick_actions: [{label:'Mở sơ đồ kiến trúc',href:'/admin/architecture',intent:'primary'},{label:'Kiểm tra RBAC matrix',href:'/admin/security',intent:'secondary'}],
    demo_highlights: [{title:'Luồng tài trợ R&D',body:'Hồ sơ pin LFP đang qua hội đồng, yêu cầu 2/3 đồng thuận.',metric:'27 tỷ VNĐ'}], legal_pillars: basePillars },
  fullstack_developer: {
    title:'Bàn làm việc phát triển',subtitle:'Backlog, build, API health, component catalog',mission:'Chuyển blueprint thành chức năng kiểm thử được.',portal_path:'/admin/development',
    kpis:[{label:'Story sẵn sàng dev',value:'31',trend:'+8',tone:'blue'},{label:'Build pass',value:'2/2',trend:'FE+BE',tone:'green'},{label:'Component dùng chung',value:'24',trend:'+6',tone:'purple'},{label:'Bug mở',value:'11',trend:'-3',tone:'amber'}],
    queues:[{title:'UI persona cần hoàn thiện',count:17,href:'/admin/development/ui',priority:'high',description:'Mỗi role cần dashboard riêng'},{title:'API cần test',count:12,href:'/admin/development/apis',priority:'medium',description:'Persona, work-queue, report endpoints'}],
    alerts:[{title:'Tránh duplicate code',description:'Bắt buộc dùng shared shell + registry.',severity:'medium'}],quick_actions:[{label:'Component catalog',href:'/admin/development/components',intent:'primary'}],demo_highlights:[{title:'Voucher marketplace',body:'Vendor IoT Lab đăng ký 18 dịch vụ công nghệ cần kiểm duyệt.',metric:'18 dịch vụ'}],legal_pillars:basePillars},
  devsecops_security:{title:'Trung tâm an toàn thông tin',subtitle:'RBAC, audit, session, vulnerability',mission:'Bảo vệ dữ liệu tài chính/công nghệ theo nguyên tắc tối thiểu quyền.',portal_path:'/admin/security',kpis:[{label:'Sự kiện audit',value:'1.248',trend:'24h',tone:'blue'},{label:'Cảnh báo cao',value:'3',trend:'cần xử lý',tone:'red'},{label:'Role có matrix',value:'17/17',trend:'đủ',tone:'green'},{label:'Phiên hoạt động',value:'142',trend:'+12',tone:'purple'}],queues:[{title:'Rà soát cấp quyền',count:7,href:'/admin/security/rbac',priority:'critical',description:'Tài khoản nội bộ đổi phòng ban'},{title:'Cảnh báo đăng nhập',count:3,href:'/admin/security/sessions',priority:'high',description:'IP mới ngoài giờ hành chính'}],alerts:[{title:'Dữ liệu chuyên gia',description:'Cần phân quyền masked view cho hội đồng/phản biện.',severity:'high'}],quick_actions:[{label:'Mở RBAC matrix',href:'/admin/security/rbac',intent:'primary'}],demo_highlights:[{title:'Audit hội đồng',body:'Biên bản chấm điểm có chữ ký số, checksum hợp lệ.',metric:'100%'}],legal_pillars:basePillars},
  data_ai_scientist:{title:'Trung tâm dữ liệu & AI',subtitle:'IOOI, pipeline, mô hình đánh giá, anomaly detection',mission:'Biến dữ liệu hồ sơ thành báo cáo điều hành và cảnh báo chính sách.',portal_path:'/admin/data-ai',kpis:[{label:'Chỉ số IOOI',value:'64',trend:'+9',tone:'green'},{label:'Dataset sạch',value:'92%',trend:'+5%',tone:'blue'},{label:'Bất thường',value:'8',trend:'cần rà soát',tone:'amber'},{label:'Báo cáo tự động',value:'12',trend:'tháng này',tone:'purple'}],queues:[{title:'Chuẩn hóa dữ liệu startup',count:46,href:'/admin/data-ai/startups',priority:'medium',description:'Thiếu KPI tăng trưởng doanh thu'},{title:'Phân tích trùng hỗ trợ',count:6,href:'/admin/data-ai/anomalies',priority:'high',description:'Dấu hiệu trùng doanh nghiệp/đề tài'}],alerts:[{title:'Mẫu dữ liệu chuyên gia',description:'Cần nhập lĩnh vực, ORCID, công bố, xung đột lợi ích.',severity:'medium'}],quick_actions:[{label:'Xem IOOI dashboard',href:'/admin/reports',intent:'primary'}],demo_highlights:[{title:'Impact tài trợ',body:'12 đề tài tạo 38 bằng sáng chế và 214 việc làm R&D.',metric:'214 jobs'}],legal_pillars:basePillars},
  natif_executive:{title:'Bảng điều hành lãnh đạo NATIF',subtitle:'Phê duyệt cuối, danh mục chiến lược, KPI ngân sách',mission:'Ra quyết định nhanh, đúng thẩm quyền, kiểm soát rủi ro chương trình.',portal_path:'/executive',kpis:[{label:'Chờ phê duyệt',value:'18',trend:'+4',tone:'amber'},{label:'Ngân sách cam kết',value:'186 tỷ',trend:'68%',tone:'blue'},{label:'Hồ sơ rủi ro cao',value:'5',trend:'legal flag',tone:'red'},{label:'Tác động dự kiến',value:'1.420 DN',trend:'+12%',tone:'green'}],queues:[{title:'Ký quyết định hỗ trợ',count:8,href:'/executive/approvals',priority:'critical',description:'Có 3 hồ sơ quá hạn SLA'},{title:'Xem khuyến nghị hội đồng',count:10,href:'/councils',priority:'high',description:'Cần quyết định phương án'}],alerts:[{title:'Hạn mức lãi suất',description:'2 hồ sơ gần vượt trần 6%/năm.',severity:'high'}],quick_actions:[{label:'Phê duyệt cuối',href:'/director',intent:'primary'}],demo_highlights:[{title:'Chương trình vật liệu mới',body:'Hội đồng đề xuất hỗ trợ dự án graphene quy mô pilot.',metric:'32 tỷ'}],legal_pillars:basePillars},
  department_manager:{title:'Điều phối phòng/ban',subtitle:'Phân công chuyên viên, lập hội đồng, duyệt tổng hợp',mission:'Tối ưu tải xử lý, bảo đảm hồ sơ đi đúng chuyên môn và hạn xử lý.',portal_path:'/dept-head',kpis:[{label:'Hồ sơ phòng xử lý',value:'42',trend:'+7',tone:'blue'},{label:'Quá hạn SLA',value:'4',trend:'-2',tone:'red'},{label:'Chuyên viên khả dụng',value:'11',trend:'ổn định',tone:'green'},{label:'Hội đồng đang mở',value:'6',trend:'+1',tone:'purple'}],queues:[{title:'Cần phân công chuyên viên',count:12,href:'/dept-head',priority:'high',description:'Hồ sơ đã được lãnh đạo chuyển phòng'},{title:'Tổng hợp sau phản biện',count:8,href:'/dept-head',priority:'medium',description:'Chờ kết luận phòng'}],alerts:[{title:'Một chuyên viên quá tải',description:'Nguyễn Minh A có 14 hồ sơ mở.',severity:'medium'}],quick_actions:[{label:'Phân công hồ sơ',href:'/dept-head',intent:'primary'}],demo_highlights:[{title:'Nhiệm vụ AI nông nghiệp',body:'Cần 2 phản biện về thị giác máy tính và chuỗi cung ứng.',metric:'2 chuyên gia'}],legal_pillars:basePillars},
  grants_orders_specialist:{title:'Chuyên viên tài trợ/đặt hàng',subtitle:'Thẩm tra hồ sơ, tổng hợp phản biện, đề xuất phương án',mission:'Bảo đảm nhiệm vụ KH&CN đủ điều kiện, đúng quy trình nghị định.',portal_path:'/grants-orders',kpis:[{label:'Hồ sơ được giao',value:'23',trend:'+5',tone:'blue'},{label:'Cần bổ sung',value:'9',trend:'DN chờ phản hồi',tone:'amber'},{label:'Đã tổng hợp',value:'14',trend:'+4',tone:'green'},{label:'Hội đồng liên quan',value:'5',trend:'tuần này',tone:'purple'}],queues:[{title:'Xét sơ bộ',count:10,href:'/officer',priority:'high',description:'Kiểm tra điều kiện tài trợ/đặt hàng'},{title:'Tổng hợp hội đồng',count:6,href:'/officer',priority:'medium',description:'Lập tờ trình lãnh đạo phòng'}],alerts:[{title:'Thiếu thuyết minh Điều 11',description:'3 hồ sơ chưa hoàn thiện mục tác động thị trường.',severity:'high'}],quick_actions:[{label:'Mở hồ sơ được giao',href:'/officer',intent:'primary'}],demo_highlights:[{title:'Đề tài pin lưu trữ',body:'Doanh nghiệp đề nghị tài trợ 27 tỷ, đã đủ 12/14 tài liệu.',metric:'12/14'}],legal_pillars:['Tài trợ/đặt hàng nhiệm vụ KH&CN']},
  voucher_startup_specialist:{title:'Chuyên viên voucher & startup',subtitle:'Marketplace, vendor, Techfest, startup KPIs',mission:'Kết nối doanh nghiệp với dịch vụ đổi mới công nghệ và hệ sinh thái khởi nghiệp.',portal_path:'/voucher-startup',kpis:[{label:'Voucher đang mở',value:'128',trend:'+24',tone:'green'},{label:'Vendor chờ xác minh',value:'17',trend:'+6',tone:'amber'},{label:'Startup theo dõi',value:'286',trend:'+31',tone:'blue'},{label:'Techfest task',value:'44',trend:'Q2',tone:'purple'}],queues:[{title:'Duyệt vendor',count:17,href:'/voucher-startup/vendors',priority:'high',description:'Cần xác minh năng lực cung cấp dịch vụ'},{title:'Redemption cần đối soát',count:22,href:'/voucher-startup/redemptions',priority:'medium',description:'Chờ chứng từ nghiệm thu'}],alerts:[{title:'Vendor vượt hạn mức',description:'2 nhà cung cấp gần chạm trần voucher quý.',severity:'medium'}],quick_actions:[{label:'Duyệt vendor',href:'/voucher-startup/vendors',intent:'primary'}],demo_highlights:[{title:'Gói đo kiểm IoT',body:'8 doanh nghiệp SME đăng ký voucher chuyển đổi số.',metric:'8 DN'}],legal_pillars:['Voucher công nghệ','Hệ sinh thái khởi nghiệp sáng tạo']},
  finance_disbursement:{title:'Tài chính & giải ngân',subtitle:'Thẩm định ngân sách, kế hoạch giải ngân, hỗ trợ lãi suất',mission:'Kiểm soát ngân sách nhà nước, tính toán hỗ trợ đúng hạn mức và chứng từ.',portal_path:'/finance',kpis:[{label:'Chờ thẩm định TC',value:'16',trend:'+3',tone:'amber'},{label:'Dự kiến giải ngân',value:'48 tỷ',trend:'tháng này',tone:'blue'},{label:'Khoản lãi hỗ trợ',value:'6.2 tỷ',trend:'đúng trần',tone:'green'},{label:'Chứng từ lỗi',value:'5',trend:'cần bổ sung',tone:'red'}],queues:[{title:'Thẩm định dự toán',count:11,href:'/finance/appraisal',priority:'high',description:'Đối chiếu định mức chi KH&CN'},{title:'Giải ngân đến hạn',count:7,href:'/finance/disbursement',priority:'critical',description:'Có hồ sơ đã ký hợp đồng'}],alerts:[{title:'Sai lệch chứng từ',description:'1 khoản chi thiết bị vượt báo giá trung bình 18%.',severity:'high'}],quick_actions:[{label:'Mở lịch giải ngân',href:'/finance/disbursement',intent:'primary'}],demo_highlights:[{title:'Hỗ trợ lãi suất ngân hàng',body:'VPBank gửi debt notice kỳ 05/2026 cho 42 khoản vay.',metric:'42 khoản'}],legal_pillars:['Hỗ trợ lãi suất vay','Tài trợ/đặt hàng nhiệm vụ KH&CN']},
  legal_risk_control:{title:'Pháp chế & kiểm soát rủi ro',subtitle:'Hợp đồng, trùng hỗ trợ, tuân thủ, ngoại lệ',mission:'Giảm rủi ro pháp lý, đảm bảo hồ sơ và hợp đồng đúng quy định.',portal_path:'/legal-risk',kpis:[{label:'Hợp đồng cần rà soát',value:'13',trend:'+4',tone:'amber'},{label:'Cảnh báo trùng',value:'6',trend:'AI flag',tone:'red'},{label:'Ngoại lệ đã xử lý',value:'21',trend:'+8',tone:'green'},{label:'Điều khoản mẫu',value:'34',trend:'chuẩn hóa',tone:'blue'}],queues:[{title:'Rà soát hợp đồng',count:13,href:'/legal-risk/contracts',priority:'high',description:'Chờ ý kiến trước ký'},{title:'Kiểm tra trùng hỗ trợ',count:6,href:'/legal-risk/duplicates',priority:'critical',description:'Đối chiếu MST, đề tài, ngân sách'}],alerts:[{title:'Xung đột lợi ích chuyên gia',description:'2 chuyên gia từng đồng tác giả với chủ nhiệm nhiệm vụ.',severity:'critical'}],quick_actions:[{label:'Mở cảnh báo rủi ro',href:'/legal-risk/duplicates',intent:'primary'}],demo_highlights:[{title:'Hợp đồng tài trợ',body:'Dự án cảm biến MEMS cần bổ sung điều khoản IP và nghiệm thu.',metric:'3 điều khoản'}],legal_pillars:basePillars},
  admin_desk:{title:'Văn thư tiếp nhận',subtitle:'OCR, kiểm tra hình thức, routing, sổ công văn',mission:'Tiếp nhận đúng chuẩn, định tuyến nhanh, không thất lạc hồ sơ/tài liệu.',portal_path:'/clerk',kpis:[{label:'Hồ sơ mới',value:'37',trend:'+12',tone:'blue'},{label:'Thiếu tài liệu',value:'14',trend:'cần nhắc',tone:'amber'},{label:'Đã chuyển tuyến',value:'29',trend:'+9',tone:'green'},{label:'Công văn đến',value:'88',trend:'tuần này',tone:'purple'}],queues:[{title:'Tiếp nhận hồ sơ',count:18,href:'/clerk',priority:'high',description:'Kiểm tra đủ bộ hồ sơ điện tử'},{title:'OCR cần xác nhận',count:9,href:'/clerk/ocr',priority:'medium',description:'Tệp scan chất lượng thấp'}],alerts:[{title:'Hồ sơ quá 24h chưa chuyển',description:'4 hồ sơ cần ưu tiên định tuyến.',severity:'high'}],quick_actions:[{label:'Mở hàng đợi tiếp nhận',href:'/clerk',intent:'primary'}],demo_highlights:[{title:'Hồ sơ startup',body:'Công ty BioNano nộp 18 file, hệ thống nhận dạng 16 file hợp lệ.',metric:'16/18'}],legal_pillars:basePillars},
  it_sysadmin_support:{title:'CNTT & hỗ trợ vận hành',subtitle:'Health, incidents, tickets, user recovery',mission:'Duy trì OMS ổn định, hỗ trợ người dùng và khôi phục sự cố nhanh.',portal_path:'/admin/it-support',kpis:[{label:'Uptime',value:'99.97%',trend:'30 ngày',tone:'green'},{label:'Ticket mở',value:'23',trend:'+5',tone:'amber'},{label:'Incident',value:'1',trend:'minor',tone:'red'},{label:'Backup OK',value:'7/7',trend:'tuần',tone:'blue'}],queues:[{title:'Ticket ưu tiên cao',count:6,href:'/admin/it-support/tickets',priority:'high',description:'Vướng đăng nhập và upload file'},{title:'Yêu cầu khôi phục tài khoản',count:4,href:'/admin/users',priority:'medium',description:'Cần xác minh danh tính'}],alerts:[{title:'Dung lượng uploads',description:'Đã dùng 78%, cần dọn file tạm.',severity:'medium'}],quick_actions:[{label:'Xem system health',href:'/admin/it-support/health',intent:'primary'}],demo_highlights:[{title:'Đồng bộ email',body:'4.000 email/tháng trong giới hạn Resend, bounce 0.4%.',metric:'0.4%'}],legal_pillars:basePillars},
  scientific_council:{title:'Hội đồng khoa học',subtitle:'Phiên họp, phiếu điểm, đồng thuận, biên bản',mission:'Đánh giá khoa học độc lập, minh bạch, có căn cứ chuyên môn.',portal_path:'/councils',kpis:[{label:'Phiên sắp họp',value:'5',trend:'7 ngày',tone:'purple'},{label:'Phiếu chưa nộp',value:'18',trend:'nhắc hạn',tone:'amber'},{label:'Đạt 2/3',value:'7',trend:'đề xuất',tone:'green'},{label:'Ý kiến bảo lưu',value:'3',trend:'cần tổng hợp',tone:'red'}],queues:[{title:'Chấm điểm nhiệm vụ',count:9,href:'/councils',priority:'high',description:'Mẫu điểm theo tiêu chí khoa học/công nghệ'},{title:'Duyệt biên bản',count:4,href:'/councils/minutes',priority:'medium',description:'Cần xác nhận nội dung phiên'}],alerts:[{title:'Xung đột lợi ích',description:'Một thành viên cần xác nhận cam kết độc lập.',severity:'high'}],quick_actions:[{label:'Vào phiên hội đồng',href:'/councils',intent:'primary'}],demo_highlights:[{title:'Hội đồng vật liệu mới',body:'7/9 thành viên đồng ý khuyến nghị tài trợ có điều kiện.',metric:'7/9'}],legal_pillars:['Tài trợ/đặt hàng nhiệm vụ KH&CN']},
  independent_expert:{title:'Chuyên gia phản biện độc lập',subtitle:'Blind review, scoring, nhận/ từ chối nhiệm vụ, hồ sơ khoa học',mission:'Cung cấp phản biện chuyên sâu, độc lập, bảo mật.',portal_path:'/expert',kpis:[{label:'Lời mời phản biện',value:'6',trend:'+2',tone:'blue'},{label:'Đang chấm',value:'4',trend:'2 sắp hạn',tone:'amber'},{label:'Đã hoàn tất',value:'19',trend:'năm nay',tone:'green'},{label:'CV hoàn thiện',value:'84%',trend:'+12%',tone:'purple'}],queues:[{title:'Phản biện cần nộp',count:4,href:'/expert/assignments',priority:'high',description:'Có 2 nhiệm vụ hạn trong 72h'},{title:'Bổ sung hồ sơ chuyên gia',count:3,href:'/expert/profile',priority:'medium',description:'ORCID, công bố Q1, lĩnh vực chuyên môn'}],alerts:[{title:'Cam kết bảo mật',description:'Cần xác nhận NDA trước khi mở hồ sơ chi tiết.',severity:'high'}],quick_actions:[{label:'Mở nhiệm vụ phản biện',href:'/expert/assignments',intent:'primary'}],demo_highlights:[{title:'Blind review AI y tế',body:'Đã ẩn thông tin doanh nghiệp; chỉ hiển thị thuyết minh kỹ thuật.',metric:'PII masked'}],legal_pillars:['Tài trợ/đặt hàng nhiệm vụ KH&CN']},
  financial_appraiser:{title:'Thẩm định tài chính độc lập',subtitle:'Định mức, dự toán, tính hợp lý chi phí',mission:'Đảm bảo ngân sách đề xuất hợp lệ, tiết kiệm, đúng định mức.',portal_path:'/financial-appraisal',kpis:[{label:'Dự toán cần thẩm định',value:'12',trend:'+3',tone:'amber'},{label:'Chi phí bất thường',value:'4',trend:'AI flag',tone:'red'},{label:'Ý kiến đã nộp',value:'28',trend:'năm nay',tone:'green'},{label:'Giá trị rà soát',value:'96 tỷ',trend:'portfolio',tone:'blue'}],queues:[{title:'Thẩm định chi phí thiết bị',count:7,href:'/financial-appraisal',priority:'high',description:'So sánh báo giá/định mức'},{title:'Rà soát nhân công R&D',count:5,href:'/financial-appraisal/labor',priority:'medium',description:'Đối chiếu định mức chuyên gia'}],alerts:[{title:'Vượt định mức hội thảo',description:'1 hồ sơ vượt 22% định mức chi hội thảo.',severity:'high'}],quick_actions:[{label:'Mở ma trận thẩm định',href:'/financial-appraisal',intent:'primary'}],demo_highlights:[{title:'Dự toán pilot line',body:'Đề xuất giảm 1.8 tỷ từ hạng mục thuê thiết bị trùng lặp.',metric:'-1.8 tỷ'}],legal_pillars:['Tài trợ/đặt hàng nhiệm vụ KH&CN','Hỗ trợ lãi suất vay']},
  independent_auditor:{title:'Kiểm toán/giám sát độc lập',subtitle:'Read-only audit, export, compliance sampling',mission:'Giám sát độc lập quá trình xử lý, giải ngân, báo cáo và nhật ký hệ thống.',portal_path:'/auditor',kpis:[{label:'Mẫu kiểm toán',value:'54',trend:'Q2',tone:'blue'},{label:'Log đã xuất',value:'18.420',trend:'hash OK',tone:'green'},{label:'Ngoại lệ',value:'7',trend:'cần giải trình',tone:'amber'},{label:'Rủi ro cao',value:'2',trend:'theo dõi',tone:'red'}],queues:[{title:'Mẫu giải ngân cần kiểm tra',count:9,href:'/auditor/disbursements',priority:'high',description:'Đối chiếu chứng từ và quyết định'},{title:'Xuất log tuân thủ',count:4,href:'/auditor/exports',priority:'medium',description:'Theo yêu cầu đoàn kiểm tra'}],alerts:[{title:'Không có quyền sửa',description:'Portal kiểm toán chỉ đọc và ghi nhận truy cập.',severity:'medium'}],quick_actions:[{label:'Mở data room',href:'/auditor',intent:'primary'}],demo_highlights:[{title:'Audit voucher',body:'Mẫu 30 giao dịch redemption, 29 hợp lệ, 1 thiếu nghiệm thu.',metric:'29/30'}],legal_pillars:basePillars},
  external_partner:{title:'Cổng doanh nghiệp/đối tác',subtitle:'Nộp hồ sơ, hợp đồng, báo cáo, voucher, ngân hàng/vendor',mission:'Theo dõi toàn bộ vòng đời hỗ trợ từ đăng ký đến giải ngân/báo cáo.',portal_path:'/apply/dashboard',kpis:[{label:'Hồ sơ của tôi',value:'5',trend:'2 đang xét',tone:'blue'},{label:'Cần bổ sung',value:'1',trend:'hạn 3 ngày',tone:'amber'},{label:'Đã phê duyệt',value:'2',trend:'32 tỷ',tone:'green'},{label:'Báo cáo đến hạn',value:'3',trend:'tháng này',tone:'red'}],queues:[{title:'Bổ sung tài liệu',count:1,href:'/apply/dashboard',priority:'high',description:'Thiếu báo cáo tài chính kiểm toán'},{title:'Báo cáo định kỳ',count:3,href:'/apply/dashboard',priority:'medium',description:'Cập nhật KPI tiến độ nhiệm vụ'}],alerts:[{title:'Hạn nộp báo cáo',description:'Báo cáo quý II đến hạn trong 5 ngày.',severity:'high'}],quick_actions:[{label:'Nộp hồ sơ mới',href:'/apply',intent:'primary'}],demo_highlights:[{title:'Hồ sơ hỗ trợ lãi suất',body:'Khoản vay thiết bị R&D đã được ngân hàng xác nhận dư nợ.',metric:'6%/năm'}],legal_pillars:basePillars}
};

export async function getPersonaDashboard(req: AuthRequest, res: Response) {
  const role = req.canonicalRole || LEGACY_TO_CANONICAL[(req.userRole || 'enterprise') as LegacyRole] || 'external_partner';
  const payload = data[role];
  res.json({ data: { role, legacy_role: CANONICAL_TO_LEGACY[role], role_label: ROLE_LABELS[role], ...payload } });
}

export async function getPortalProfile(req: AuthRequest, res: Response) {
  const role = req.canonicalRole || LEGACY_TO_CANONICAL[(req.userRole || 'enterprise') as LegacyRole] || 'external_partner';
  const payload = data[role];
  res.json({ data: { role, legacy_role: CANONICAL_TO_LEGACY[role], role_label: ROLE_LABELS[role], portal_path: payload.portal_path, legal_pillars: payload.legal_pillars } });
}
